---
sudo: false
language: ruby
cache: bundler
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
env:
  matrix:
    - PUPPET_VERSION="~> 3.4.3"
    - PUPPET_VERSION="~> 3.8.0" FUTURE_PARSER=yes
    - PUPPET_VERSION="~> 4.2.0"
matrix:
  fast_finish: true
  exclude:
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.4.0"
